spring:
  application:
    name: technews-service # Service registers under this name
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# HTTP Server
server:
  port: 4000   # HTTP (Netty) port
  address: 0.0.0.0

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
      healthcheck:
        enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: false


info:
  app:
    name: technews-service
    description: Spring Cloud Random Tech News Generator
    version: 2.0.0-SNAPSHOT

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: DEBUG
    com.apress.prospringmvc.technews: DEBUG